# Generated by Django 5.2.14 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('success', 'Completado'), ('error', 'Error')], default='running', max_length=20)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_new', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ejecución del scraper',
                'verbose_name_plural': 'Ejecuciones del scraper',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source', models.CharField(choices=[('arbeitnow', 'Arbeitnow'), ('remotive', 'Remotive'), ('seed', 'Seed Data')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('remote', models.BooleanField(db_index=True, default=False)),
                ('date_posted', models.DateField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oferta de trabajo',
                'verbose_name_plural': 'Ofertas de trabajo',
                'ordering': ['-date_posted', '-fetched_at'],
                'indexes': [models.Index(fields=['source', 'remote'], name='jobs_job_source_8dc650_idx'), models.Index(fields=['date_posted', 'source'], name='jobs_job_date_po_a6fb7b_idx')],
            },
        ),
    ]
